GET http://localhost:3000/users

###

GET http://localhost:3000/users/67989c19881d22f38057cf44

### 
POST http://localhost:3000/users/ HTTP/1.1 
Content-Type: application/json

{   
    "firstName": "compay",
    "lastName": "tokpah",
    "email": "tokpahcompay@gmail.com",
    "favoriteColor": "orange",
    "birthday": "1996-01-01"
}

###

PUT http://localhost:3000/users/679892f9bcdaa999bf29b831 HTTP/1.1 
content-type: application/json

{ 
    "firstName": "James",
    "lastName": "Brown",
    "email": "jamesbrown@gmail.com",
    "favoriteColor": "brown",
    "birthday": "1996-01-12"
}

###

DELETE http://localhost:3000/users/67988d07ff90afa16572e18a HTTP/1.1